### ISSUE TITLE
can't find  "Duplicate" on upper right corner

### ISSUE THREAD

**Issue by VectorZhao** [doutv/Auto-GPT-Notion#10]
I can not find "Duplicate" on upper right corner.

**Comment by doutv** [comment]
It's weird. I already allow duplicate as template, but I cannot see "Duplicate" on upper right corner either.

![image](https://github.com/doutv/Auto-GPT-Notion/assets/20609724/e1c9193d-7d1a-4e6e-8b64-89d29d063f20)

**Comment by doutv** [comment]
You can manually create a database, with the following 3 properties:
```
Title: Title
Tags: Multi-select
Summary: Text
```

**Comment by VectorZhao** [comment]
Thank you, but I am a beginner with Notion. Templates are the best choice for me.

**Comment by doutv** [comment]
https://doutv.notion.site/doutv/a90461761f46498ea2efc4435e54091b?v=d34c7e21836f4a3b8293de74138f38e5
Can you try to duplicate this database?

**Comment by VectorZhao** [comment]
> https://doutv.notion.site/doutv/a90461761f46498ea2efc4435e54091b?v=d34c7e21836f4a3b8293de74138f38e5 Can you try to duplicate this database?

yes, cheers
