### ISSUE TITLE
This plugin doesn't work properly i believe

### ISSUE THREAD

**Issue by q-sag** [doutv/Auto-GPT-Notion#11]
![image](https://github.com/doutv/Auto-GPT-Notion/assets/93086196/2c078199-ea24-4c28-ae05-385086f68b07)

So any command AutoGPT tries to execute from provided list in this repository isn't working.

**Comment by doutv** [comment]
Which Auto-GPT commit/release are you using?

**Comment by q-sag** [comment]
Latest, Auto-GPT v0.3.1

**Comment by q-sag** [comment]
@doutv  i believe it may be a problem of database, as i created my own. Can you please allow to duplicate your template ? so i can test it 

![image](https://github.com/doutv/Auto-GPT-Notion/assets/93086196/ca4c3109-bb91-4769-88fb-405ce8bfc810)

**Comment by doutv** [comment]
You can try to duplicate this database: 
https://doutv.notion.site/a90461761f46498ea2efc4435e54091b?v=d34c7e21836f4a3b8293de74138f38e5&pvs=4

The previous one is broken, I cannot fix.
