### ISSUE TITLE
worked yesterday but not today

### ISSUE THREAD

**Issue by scenaristeur** [doutv/Auto-GPT-Notion#13]
Hi ! 
Great plugin ;-)
i could use auto-gpt-notion yesterday but today, i have this message. 
Any idea ? thxs

![image](https://github.com/doutv/Auto-GPT-Notion/assets/4020744/4845d1da-e28e-460b-b254-3b3061b45635)

**Comment by doutv** [comment]
Thanks for your feedback. This problem will be fixed in PR https://github.com/doutv/Auto-GPT-Notion/pull/12

**Comment by scenaristeur** [comment]
thxs. Autogpt stable is now 0.4.0, is Notion plugin compatible ?

**Comment by doutv** [comment]
I think it is compatible, but I haven't tested it thoroughly.
