### ISSUE TITLE
nonetype' object has no attribute 'get'

### ISSUE THREAD

**Issue by Lushin415** [doutv/Auto-GPT-Notion#4]
Throws an error: nonetype' object has no attribute 'get'. Any ideas how to fix this?

**Comment by Lushin415** [comment]
> Throws an error: nonetype' object has no attribute 'get'. Any ideas how to fix this?

It seems I figured out what was the matter. It was the tables. He cannot read them. The question follows: How to make him read and understand tables, any ideas?

**Comment by doutv** [comment]
Currently, it can only read `plain_text` inside `rich_text`.  I have no idea to read other types of input.

See https://developers.notion.com/reference/rich-text for more details.
