### ISSUE TITLE
Request: Include source URL links

### ISSUE THREAD

**Issue by devchamps** [doutv/Auto-GPT-Notion#5]
using the following format

![image](https://user-images.githubusercontent.com/5169166/235832740-1ff085a5-32c0-47a2-a0da-91702631e540.png)

**Comment by doutv** [comment]
Good idea! Just add one column in database and change few lines of code.

The current implementation requires fixed database structure(properties). I am thinking how to let Auto-GPT read and understand database structure.

For example, the current Notion plugin requires 3 database properties `Title`, `Summary`, `Tags`.  
Add a property `source` require code changes.

If it can understand database structure, add a new property will not require code changes.
