### ISSUE TITLE
Is it possible add notion ai functions?

### ISSUE THREAD

**Issue by giyeol** [doutv/Auto-GPT-Notion#6]
Is it possible to add a feature to use Notion AI like "https://github.com/Vaayne/notionai-py"?

**Comment by doutv** [comment]
I don't think it is necessary. I have tried Notion AI and it performs just like GPT-3.5. 

However, if you are interested, you are welcome to build together! You can make a pr for this feature.

It is possible and easy to add Notion AI feature:
1. Install & import this repo https://github.com/Vaayne/notionai-py.
2. Write functions to wrap its API.
3. Add new commands.
