### ISSUE TITLE
Error: Body Failed validation

### ISSUE THREAD

**Issue by peitz7** [doutv/Auto-GPT-Notion#9]
I have been receiving this error: SYSTEM:  Command notion_create_page returned: Error: body failed validation. Fix one: body.parent.database_id should be a valid uuid, instead was `"f5820afe77ee4c589e91903f956bdda1?v=9a3e53af8585464db3e...`. body.parent.page_id should be defined, instead was `undefined`.

What do I need to do to fix this? I have double checked the notion token and Notion database ID and it matches exactly what the instructions explain to do.

Any help would be appreciated.

**Comment by doutv** [comment]
NOTION_DATABASE_ID should not include `?v=...`

**Comment by doutv** [comment]
I change the example in README a little bit. You can refer to https://github.com/doutv/Auto-GPT-Notion#notion-settings

**Comment by peitz7** [comment]
Awesome, it worked thank you
